import type { Metadata } from "next";
import "./globals.css";
import TypekitLoader from '@/app/components/Elements/TypekitLoader'
import Header from "./components/Layouts/Header/Header";


export const metadata: Metadata = {
  title: "Kazuki_Makida-Portfolio",
  description: "Generated by Kazuki_Makida",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <head>
        {/* <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,200&display=optional" /> */}
        <TypekitLoader/>
      </head>
      <body className="font-garamond">
        <Header/>
        {children}
        </body>
    </html>
  );
}
